name: build

on:
  push:
    branches:
      - '*'

jobs:

  build:
    name: Build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: msbuild
