name: build

on:
  push:
    branches:
      - '*'

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: | 
            4.5.x
      - name: Build
        run: msbuild
